image:
  longhorn:
    engine:
      tag: v1.6.0
    manager:
      tag: v1.6.0
    ui:
      tag: v1.6.0

# Service configuration
service:
  ui:
    type: LoadBalancer
    nodePort: null

# Ingress disabled, using LoadBalancer
ingress:
  enabled: false

# Persistence settings
persistence:
  defaultClass: true
  defaultClassReplicaCount: 2
  defaultDataLocality: best-effort

# Default settings
defaultSettings:
  backupTarget: ""
  backupTargetCredentialSecret: ""
  allowRecurringJobWhileVolumeDetached: true
  createDefaultDiskLabeledNodes: true
  defaultDataPath: "/var/lib/longhorn/"
  replicaSoftAntiAffinity: false
  storageOverProvisioningPercentage: 100
  storageMinimalAvailablePercentage: 25
  upgradeChecker: true
  defaultReplicaCount: 2
  guaranteedEngineManagerCPU: 12
  guaranteedReplicaManagerCPU: 12
  kubernetesClusterAutoscalerEnabled: false
  orphanAutoDeletion: true
  storageNetwork: ""

# Resources for Longhorn components
longhornManager:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

longhornDriver:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi

longhornUI:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi
