persistence:
  defaultClass: true
  defaultClassReplicaCount: 1  # Reduced for RPi setup
  defaultDataLocality: disabled  # Better for small clusters

# Default settings optimized for RPi
defaultSettings:
  createDefaultDiskLabeledNodes: true
  defaultDataPath: "/var/lib/longhorn/"

preUpgradeChecker:
  jobEnabled: false

# Resources optimized for RPi
longhornManager:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 300m
      memory: 256Mi

longhornDriver:
  resources:
    requests:
      cpu: 25m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 128Mi

longhornUI:
  resources:
    requests:
      cpu: 25m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 128Mi

