persistence:
  defaultClass: true
  defaultClassReplicaCount: 1 
  defaultDataLocality: disabled  

defaultSettings:
  createDefaultDiskLabeledNodes: false
  defaultDataPath: "/var/lib/longhorn/"
  defaultReplicaCount: 1
  guaranteedInstanceManagerCPU: 4

preUpgradeChecker:
  jobEnabled: false

longhornManager:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 300m
      memory: 256Mi
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule

longhornDriver:
  resources:
    requests:
      cpu: 25m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 128Mi

longhornUI:
  resources:
    requests:
      cpu: 25m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 128Mi

ingress:
  enabled: false 

