apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-production
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: 7.0.19
    helm:
      valueFiles:
        - $values/infrastructure/grafana/values-production.yaml
  sources:
    - repoURL: https://github.com/steviepreston/minilab.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
