apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-production
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 55.5.0
      helm:
        valueFiles:
          - $values/infrastructure/prometheus/values-production.yaml
    - repoURL: https://github.com/steviepreston/minilab.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
