prometheus:
  prometheusSpec:
    resources:
      requests:
        cpu: 500m
        memory: 2Gi
      limits:
        cpu: 2000m
        memory: 4Gi
    retention: 30d
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn-storageclass
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi
    nodeSelector:
      kubernetes.io/os: linux

alertmanager:
  enabled: true

# Disable Grafana (Deployed seperately)
grafana:
  enabled: false

# Node Exporter
nodeExporter:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

# Kube State Metrics
kubeStateMetrics:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

# Prometheus Operator
prometheusOperator:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

prometheus-node-exporter:
  extraArgs:
    - --collector.thermal_zone
    - --collector.hwmon
  hostRootFsMount:
    enabled: true
    mountPropagation: HostToContainer

