prometheus:
  prometheusSpec:
    resources:
      requests:
        cpu: 500m
        memory: 2Gi
      limits:
        cpu: 2000m
        memory: 4Gi
    retention: 30d
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn-storageclass
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi
    nodeSelector:
      kubernetes.io/os: linux

# Disable Grafana and AlertManager (Deployed seperately)
grafana:
  enabled: false
alertmanager:
  enabled: false

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 'alertmanager-production.monitoring.svc.cluster.local:9093'
      
# Node Exporter
nodeExporter:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

# Kube State Metrics
kubeStateMetrics:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

# Prometheus Operator
prometheusOperator:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

prometheus-node-exporter:
  extraArgs:
    - --collector.thermal_zone
    - --collector.hwmon
  hostRootFsMount:
    enabled: true
    mountPropagation: HostToContainer

groups:
- name: test-alerts
  rules:
  - alert: TestAlert
    expr: vector(1)
    for: 1s
    labels:
      severity: test
    annotations:
      summary: "This is a test alert to check Alertmanager configuration."
