resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000

rbac:
  create: true

serviceAccount:
  create: true

webhook:
  enabled: true

