storage:
  type: elasticsearch

elasticsearch:
  enabled: true
  replicas: 2 
  persistence:
    enabled: true
    size: 25Gi
    storageClass: longhorn-storageclass

allInOne:
  enabled: true
  image:
    tag: "1.55.0"
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
  args:
    - --es.server-urls=http://elasticsearch:9200
    - --es.num-shards=3
    - --es.num-replicas=1
    - --collector.otlp.enabled=true
    - --query.max-clock-skew-adjustment=0s

esIndexCleaner:
  enabled: true
  schedule: "55 23 * * *"
  numberOfDays: 14  

collector:
  enabled: false
query:
  enabled: false
agent:
  enabled: false
cassandra:
  enabled: false

serviceMonitor:
  enabled: true
  additionalLabels:
    app.kubernetes.io/part-of: kube-prometheus-stack

