# Jaeger Operator values
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000

rbac:
  create: true

serviceAccount:
  create: true

webhook:
  enabled: true

# Jaeger Instance configuration (used by the CRD, not the Helm chart)
instance:
  strategy: allInOne
  allInOne:
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        cpu: 800m
        memory: 512Mi
  storage:
    type: memory
    options:
      memory:
        max-traces: 50000
