deploymentMode: SingleBinary

singleBinary:
  replicas: 1
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi
  persistence:
    enabled: true
    storageClass: longhorn-storageclass
    size: 20Gi
  extraArgs:
    - -config.expand-env=true
  extraEnv:
    - name: LOKI_TRACING_ENABLED
      value: "true"

# Component disabling
write:
  replicas: 0
read:
  replicas: 0
backend:
  replicas: 0
gateway:
  enabled: false
ingester:
  replicas: 0
distributor:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
compactor:
  replicas: 0
ruler:
  replicas: 0

# Loki configuration
loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
    path_prefix: /var/loki
  storage:
    type: filesystem
    filesystem:
      directory: /var/loki/chunks
  schemaConfig:
    configs:
      - from: 2024-04-01
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: index_
          period: 24h
  limits_config:
    retention_period: 336h
    ingestion_rate_mb: 10
    ingestion_burst_size_mb: 20

# Disable caches and Tests
chunksCache:
  enabled: false
resultsCache:
  enabled: false
test:
  enabled: false

# Monitoring
monitoring:
  selfMonitoring:
    enabled: true
    grafanaAgent:
      installOperator: false
  serviceMonitor:
    enabled: true
    labels:
      app.kubernetes.io/part-of: kube-prometheus-stack
    interval: 15s
    scrapeTimeout: 10s

