resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1Gi

# No persistence for now (data will be lost on restart)
# TODO: Install LongHorn
persistence:
  enabled: false

# Security
securityContext:
  runAsNonRoot: true
  runAsUser: 10001
  fsGroup: 10001

# Service configuration
service:
  type: ClusterIP
  port: 3100

# Loki configuration
loki:
  commonConfig:
    replication_factor: 1
  
  storage:
    type: 'filesystem'
    filesystem:
      chunks_directory: '/tmp/loki/chunks'
      rules_directory: '/tmp/loki/rules'
  
  schemaConfig:
    configs:
      - from: 2025-01-01
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: index_
          period: 24h

# Single binary mode for RPi
deploymentMode: SingleBinary
singleBinary:
  replicas: 1
