deploymentMode: SingleBinary

singleBinary:
  replicas: 1
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi

# DISABLE other components when using SingleBinary
write:
  replicas: 0
read:
  replicas: 0
backend:
  replicas: 0

# Loki configuration
loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: 'filesystem'
  schemaConfig:
    configs:
      - from: 2024-04-01
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: index_
          period: 24h

# Test configuration
test:
  enabled: false

# Monitoring disabled for now
# FIX: Enable Monitoring
monitoring:
  selfMonitoring:
    enabled: false
    grafanaAgent:
      installOperator: false

# Gateway disabled
gateway:
  enabled: false
