apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aoa-production
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/steviepreston/minilab.git
    targetRevision: HEAD
    path: platform/environments/production
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

